name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: 📗 Profile
        uses: Fernigithub/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: header, activity, repositories
          plugin_lines: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, dockerfile, makefile, cmake, shell, gnuplot, glsl, objective-c, jupyter notebook, ruby, scss, javascript

      - name: Checkout repo
        uses: actions/checkout@v2
        # We need full history to introspect created/updated:
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - uses: actions/cache@v2
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Commit and push if README changed
        run: |-
          git pull
          git diff
          git config --global user.email "readme-bot@example.com"
          git config --global user.name "README-bot"
          git diff --quiet || (git add README.md && git commit --amend --no-edit)
          git push --force
